name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: [{cron: '38 11 * * 6'}]

jobs:
  build:
    strategy:
      matrix:
        boards:
          - 'nrf52840-dk'
          - 'nrf52840-dongle'
          - 'nrf52840-mdk-dongle'
          - 'solo'
        flags:
          - ''
          - '--release'
          - '--release --log=error'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: build --board=${{ matrix.board }} ${{ matrix.flags }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: test
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: fmt
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: clippy
